### ISSUE TITLE
U tool is good. But...

### ISSUE THREAD

**Issue by deepblacksky** [KeithYin/mycodes#1]
But there is a important things that U need generate train_txt file and the test_txt file. If my dataSet don't have this file, I can't use this tool. Just like CIFAR DATASET.  
Another issue is about `imread()` . `matplotlib.pyplot.imread`  only have good performance on PNG image. I think you can use 'cv2.imread' or PIL in big image data. :)
Above are my personal views. U can close this issue in any time.
Anyway, I give you a star. 👍

**Comment by keithyin** [comment]
@deepblacksky  Thanks for your patient comment. Due to some people who couldn't install opencv , such like me. I am going to using scikit-image instead of opencv. THere are a lot of different ways to generate train_txt and test_txt file according the different dataset, So it's hard to design common framework to do that, but i will working on it. Thanks again.
